baseURL = 'https://lucas-cauhe.github.io/'
languageCode = 'en-us'
title = 'Lucas Cauh√© Portfolio'
[module]
  [[module.imports]]
    path = "github.com/Fastbyte01/KeepIt"
      [[module.imports.mounts]]
        disableWatch = false
        lang = ''
        source = 'data'
        target = 'data'
      [[module.imports.mounts]]
        disableWatch = false
        lang = ''
        source = 'layouts'
        target = 'layouts'
      [[module.imports.mounts]]
        disableWatch = false
        lang = ''
        source = 'i18n'
        target = 'i18n'
      [[module.imports.mounts]]
        disableWatch = false
        lang = ''
        source = 'archetypes'
        target = 'archetypes'
      [[module.imports.mounts]]
        disableWatch = false
        lang = ''
        source = 'assets'
        target = 'assets'
